name:                exercise3
version:             0.1.0.0
github:              CGenie/exercise3
license:             BSD3
author:              Przemek Kamiński
maintainer:          cgenie@gmail.com
copyright:           Przemek Kamiński

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/CGenie/exercise3#readme>

dependencies:
- base >= 4.7 && < 5
- monad-loops >= 0.4.3

library:
  source-dirs: src

executables:
  exercise3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercise3

tests:
  exercise3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercise3
